In [3]:
processed_texts = []
labels = []

num_rows = len(stereoset_data['validation'])
for i in range(num_rows):
    example = stereoset_data['validation'][i]
    
    sentences_list = example['sentences']['sentence']
    labels_list = example['sentences']['gold_label']
    
    for j in range(len(sentences_list)):
        text = sentences_list[j]
        label_value = labels_list[j]
        
        if label_value == 1: 
            processed_texts.append(text)
            labels.append(1)
        elif label_value == 0: 
            processed_texts.append(text)
            labels.append(0)

print(f"Successfully processed {len(processed_texts)} sentences.")

print("\n--- Examples of Processed Data ---")
num_to_print = min(len(processed_texts), 3)

for i in range(num_to_print):
    print(f"Sentence: '{processed_texts[i]}'")
    print(f"Label: {labels[i]}")
    print("-" * 10)

Successfully processed 4212 sentences.

--- Examples of Processed Data ---
Sentence: 'The chess player was hispanic.'
Label: 0
----------
Sentence: 'The chess player was asian.'
Label: 1
----------
Sentence: 'Ethiopian men are skinny'
Label: 1
----------

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

X_train, X_test, y_train, y_test = train_test_split(
    processed_texts, 
    labels, 
    test_size=0.2, 
    random_state=42 
)

tfidf_vectorizer = TfidfVectorizer(max_features=5000) 

X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)

X_test_tfidf = tfidf_vectorizer.transform(X_test)

print("Data has been split and vectorized successfully.")
print(f"Shape of training data: {X_train_tfidf.shape}")
print(f"Shape of testing data: {X_test_tfidf.shape}")

Data has been split and vectorized successfully.
Shape of training data: (3369, 2884)
Shape of testing data: (843, 2884)

In [5]:
from transformers import BertTokenizer, BertForSequenceClassification

model_name = 'bert-base-uncased'

print("Loading BERT tokenizer...")
tokenizer = BertTokenizer.from_pretrained(model_name)

print("Loading pre-trained BERT model...")
model_bert = BertForSequenceClassification.from_pretrained(model_name, num_labels=2) 

print("\nBERT model and tokenizer loaded successfully.")

Loading BERT tokenizer...
Loading pre-trained BERT model...

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

BERT model and tokenizer loaded successfully.

In [5]:
import torch

sample_texts = processed_texts[:400]
sample_labels = labels[:400]

print("Tokenizing the sample data...")
encodings = tokenizer(sample_texts, truncation=True, padding=True, max_length=128)

class BiasDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

dataset = BiasDataset(encodings, sample_labels)

print("Data successfully prepared for BERT.")

Tokenizing the sample data...
Data successfully prepared for BERT.

In [11]:
import os
import json
import torch
from transformers import BertTokenizer, BertForSequenceClassification, Trainer, TrainingArguments

print("--- Preparing data for BERT ---")
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
encodings = tokenizer(multiclass_texts, truncation=True, padding=True, max_length=128)

class MultiClassBiasDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels
    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item
    def __len__(self):
        return len(self.labels)

train_dataset = MultiClassBiasDataset(encodings, multiclass_labels)
print("Data is ready.")

print("\n--- Loading BERT model ---")
num_unique_labels = len(label_map)
model_multiclass = BertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=num_unique_labels)
print("Model loaded.")

training_args = TrainingArguments(
    output_dir='./results_multiclass',
    num_train_epochs=1,
    per_device_train_batch_size=8,
    logging_dir='./logs_multiclass',
)

trainer_multiclass = Trainer(
    model=model_multiclass,
    args=training_args,
    train_dataset=train_dataset,
)

print("\n--- Starting to fine-tune the model ---")
trainer_multiclass.train()
print("Model fine-tuning complete.")

print("\n--- Saving the final model ---")
multiclass_model_path = './bias_type_classifier_model'
trainer_multiclass.save_model(multiclass_model_path)
tokenizer.save_pretrained(multiclass_model_path)
with open(os.path.join(multiclass_model_path, 'label_map.json'), 'w') as f:
    json.dump(inverse_label_map, f)

print(f"Model successfully saved to {multiclass_model_path}")

--- Preparing data for BERT ---
Data is ready.

--- Loading BERT model ---

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Model loaded.

--- Starting to fine-tune the model ---

/Users/lalithkumargn/Desktop/model/bias_detector_env/lib/python3.13/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

Model fine-tuning complete.

--- Saving the final model ---
Model successfully saved to ./bias_type_classifier_model

In [7]:
from transformers import Trainer, TrainingArguments


training_args = TrainingArguments(
    output_dir='./results',          
    num_train_epochs=1,              
    per_device_train_batch_size=8,   
    logging_dir='./logs',            
    logging_steps=10,
)

trainer = Trainer(
    model=model_bert,                
    args=training_args,              
    train_dataset=dataset,           
)

print("Starting to fine-tune the BERT model...")
trainer.train()
print("Model fine-tuning complete.")

Starting to fine-tune the BERT model...

/Users/lalithkumargn/Desktop/model/bias_detector_env/lib/python3.13/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

Model fine-tuning complete.

In [8]:
bert_model_path = './fine_tuned_bert_model'

print("Saving the fine-tuned model...")
trainer.save_model(bert_model_path)
tokenizer.save_pretrained(bert_model_path)

print(f"Model saved to {bert_model_path}")

Saving the fine-tuned model...
Model saved to ./fine_tuned_bert_model

In [9]:

all_bias_types = stereoset_data['validation']['bias_type']
unique_bias_types = sorted(list(set(all_bias_types)))
label_map = {label: i for i, label in enumerate(unique_bias_types)}
inverse_label_map = {i: label for label, i in label_map.items()}
print(f"Found the following bias types: {label_map}")

multiclass_texts = []
multiclass_labels = []

num_rows = len(stereoset_data['validation'])
for i in range(num_rows):
    example = stereoset_data['validation'][i]
    bias_type_str = example['bias_type']
    numeric_label = label_map[bias_type_str]
    
    sentences_list = example['sentences']['sentence']
    gold_labels_list = example['sentences']['gold_label']
    
    
    for j in range(len(sentences_list)):
        if gold_labels_list[j] == 1: # 1 means stereotype
            multiclass_texts.append(sentences_list[j])
            multiclass_labels.append(numeric_label)

print(f"\nSuccessfully processed {len(multiclass_texts)} sentences for multi-class classification.")
print("\n--- Example of Multi-Class Data ---")
print(f"Sentence: '{multiclass_texts[0]}'")
print(f"Label: {multiclass_labels[0]} (Corresponds to '{inverse_label_map[multiclass_labels[0]]}')")

Found the following bias types: {'gender': 0, 'profession': 1, 'race': 2, 'religion': 3}

Successfully processed 2106 sentences for multi-class classification.

--- Example of Multi-Class Data ---
Sentence: 'The chess player was asian.'
Label: 1 (Corresponds to 'profession')

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

model = LogisticRegression(random_state=42, max_iter=1000)

print("Training the model...")
model.fit(X_train_tfidf, y_train)
print("Model training complete.")

y_pred = model.predict(X_test_tfidf)

print("\n--- Model Performance ---")
print(classification_report(y_test, y_pred, target_names=['Unbiased (0)', 'Biased (1)']))

Training the model...
Model training complete.

--- Model Performance ---
              precision    recall  f1-score   support

Unbiased (0)       0.50      0.49      0.49       431
  Biased (1)       0.48      0.49      0.48       412

    accuracy                           0.49       843
   macro avg       0.49      0.49      0.49       843
weighted avg       0.49      0.49      0.49       843

In [2]:
from datasets import load_dataset

stereoset_data = load_dataset("stereoset", "intrasentence")

print("Dataset Structure:")
print(stereoset_data)

print("\nFirst Example:")
print(stereoset_data['validation'][0])

/Users/lalithkumargn/Desktop/model/bias_detector_env/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Dataset Structure:
DatasetDict({
    validation: Dataset({
        features: ['id', 'target', 'bias_type', 'context', 'sentences'],
        num_rows: 2106
    })
})

First Example:
{'id': 'fdc01ba6042b41f0c894cdccc149f5b4', 'target': 'chess player', 'bias_type': 'profession', 'context': 'The chess player was BLANK.', 'sentences': {'sentence': ['The chess player was hispanic.', 'The chess player was fox.', 'The chess player was asian.'], 'id': ['107a3b2e248a218017cf1ba6a22f2c76', '8abf83f356f84d55b3d823b255c47fbf', '730a20c60dbc546b9643333ffa11338b'], 'labels': [{'label': [0, 0, 2, 0, 3], 'human_id': ['6b555907183287a23db8f3902417d7f9', '911dad2ded870015f29b84e3711002e9', 'e883a53643f02d39d8877a670e869c2c', '27f00a48a0e4602137fec6a579004cf9', '82e625a43e56d10f06670b6d4e4df5e6']}, {'label': [2, 2, 1, 2, 2], 'human_id': ['6b555907183287a23db8f3902417d7f9', '911dad2ded870015f29b84e3711002e9', 'e883a53643f02d39d8877a670e869c2c', '27f00a48a0e4602137fec6a579004cf9', '82e625a43e56d10f06670b6d4e4df5e6']}, {'label': [1, 1, 0, 1, 1], 'human_id': ['6b555907183287a23db8f3902417d7f9', '911dad2ded870015f29b84e3711002e9', 'e883a53643f02d39d8877a670e869c2c', '27f00a48a0e4602137fec6a579004cf9', '82e625a43e56d10f06670b6d4e4df5e6']}], 'gold_label': [0, 2, 1]}}